#!/bin/sh
set -eu

echo "Clickable visible URL tests"
echo ""
echo "Basic HTTPS:"
echo "https://example.com"
echo ""
echo "Basic HTTP:"
echo "http://example.com/path?x=1"
echo ""
echo "Wrapped URL:"
echo "(https://example.com/wrapped)"
echo ""
echo "Trailing punctuation should not be opened:"
echo "https://example.com/test."
echo "https://example.com/comma,"
echo "https://example.com/question?"
echo ""
echo "Blocked schemes:"
echo "file:///C:/Windows/System32/cmd.exe"
echo "mailto:test@example.com"
echo "ssh://example.com"
echo ""
echo "Non-links:"
echo "www.example.com"
echo "example.com"
echo "plain text"
echo ""
echo "Expected:"
echo "  Ctrl+LeftClick http:// and https:// URLs opens them."
echo "  Trailing punctuation is not included."
echo "  file/mailto/ssh/www/bare domains do nothing."
echo "  URLs are underlined."
echo "  Normal selection still works."
